language: csharp
solution: MakersAcademy.Bank.sln
install:
  - nuget restore MakersAcademy.Bank.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release MakersAcademy.Bank.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./MakersAcademy.Bank.Tests/bin/Release/MakersAcademy.Bank.Tests.dll